spring:

  datasource:
    url: jdbc:mysql://localhost:3306/talents
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: merfoukyassir200@gmail.com
    password: hpjracbdjxewsmss
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

suggestions:
  queue: suggestions
  exchange: suggestions
  routing-key: suggestions

activation:
  queue: activation
  exchange: activation
  routing-key: activation

reset-password:
  queue: reset-password
  exchange: reset-password
  routing-key: reset-password

cloudinary:
  cloud_name: djcdpsyie
  api_key: 626114823797125
  api_secret: sLt96EchLM8j5yfS6sOupogUfTQ

jwt:
  secret-key: $2y$10$PO5X69nUUv02TkQABvi1buhZl1ELFjaV1Vmzs0hn2bQj0DDZ4/ooS
  life-time:
    access-token: 60
    refresh-token: 300

frontend:
  confirmation-url: http://localhost:4200/auth/account/confirmation
  reset-password-url: http://localhost:4200/auth/reset-password/
  job-url: http://localhost:4200/job/

uploads:
  image:
    path: uploads/talents/images

talents:
  images:
    url: http://localhost:8080/api/v1/talents/image/

cities:
  file: src/main/resources/moroccan.cities.json

error:
  message:
    bad-credentials: Email or Password incorrect
    disabled-user: User account is disabled, please contact admin for more details

notification:
  message:
    test: This is a test notification for you, please forget it.
    meet: You have a [MEET TYPE] meet at [DATE]
    verification-request: The [USER TYPE] [FIRST NAME] [LAST NAME] sent a verification request to the admins.
    verification-confirmation: You have been verified by the admins, welcome to our platform.
    job-start-process-request: Client [FIRST NAME] [LAST NAME] sent a request for starting his job process.
    job-start-selection: Your job is in selection state now, admin will start selection of talents.
    job-start-approving: Your job is in approving state now, please check the selected talents.
    job-client-close: Client [FIRST NAME] [LAST NAME] has closed his job, please check the job.
    job-admin-close: Your job has been closed by the admin, please check the job.
    job-interview-request: Client [FIRST NAME] [LAST NAME] sent a request for interview with talent [FIRST NAME 2] [LAST NAME 2] for his job offer.


